### ISSUE TITLE
not working in ASP

### ISSUE THREAD

**Issue by pablito** [arton/RScript22#1]
the following code:
`<script runat="server" language="RubyScript.2.2">`
`@Response.Write instance_variables.inspect`
`</script>`
put in an ASP page gives the following error:

`RScript error '00000200'`
`undefined method 'Write' for nil:NilClass`
`/hello.asp, line 2`
`@Response.Write instance_variables.inspect`
`^`

the expected answer (using rubyscript.1.9) is:
`[:@Application, :@ObjectContext, :@Request, :@Response, :@Server, :@Session]`

**Comment by arton** [comment]
Thank you for your bug report.
I will investigate at this week end.

**Comment by arton** [comment]
This issue is only surface of the problem. Because of ASP creates a request handler on its own worker thread, and current ruby does not export thread initializer.
Therefore after receiving the first request, following requests are all crushed because of the lack of ruby's thread objects.
I wonder if you could wait to update RScript 19 to 22 until ruby's C thread API was ready or upgraded to RScript20 for Ruby-2.0, 2.1. RScript20 has same software architecture as RScript19 but adjust for Ruby 2.x C-API (I did not link it with ruby 2.2, however it's possible to link with ruby 2.2).

**Comment by pablito** [comment]
Thanks Arton, I moved to ruby 2.1
